<?php

namespace AppBundle\Repository;

/**
 * SearchingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SearchingRepository extends \Doctrine\ORM\EntityRepository
{
}
