<?php

namespace AppBundle\Repository;

/**
 * searchingForRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class searchingForRepository extends \Doctrine\ORM\EntityRepository
{
}
